# rails _5.2.4.3_ new .bcl_up_server_app --database=mysql
# rm .bcl_up_server_app/config/database.yml # use ENV for database configuration
# docker compose build
# docker compose up app
services:
  app: &app
    build:
      context: .
      args:
        - RAILS_ENV=${RAILS_ENV:-development}
    image: cul-it/bcl-up_server_dev:v1
    container_name: bcl-up_server-app-dev
    env_file: .env
    environment:
      - RAILS_ENV=${RAILS_ENV:-development}
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    volumes:
      - .env:/app/cul-it/bcl-up_server-webapp/.env:ro

  mysql:
    image: mariadb:10.6 # Not specifying version causes a runtime error: "undefined method `encoding' for -0.0:BigDecimal"
    restart: always
    container_name: bcl-up-bcl_up_server-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE_NAME_PREFIX}_development
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - db-mysql-data:/var/lib/mysql/data

volumes:
  db-mysql-data:
