default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

  username: <%= ENV.fetch('POSTGRES_USER', 'postgres') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', '') %>
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
  port: <%= ENV.fetch('POSTGRES_PORT', 5432) %>

development:
  <<: *default
  database: bcl_up_server_development

test:
  <<: *default
  database: bcl_up_server_test

integration:
  <<: *default
  database: bcl_up_server_integration

staging:
  <<: *default
  database: bcl_up_server_staging

production:
  <<: *default
  database: bcl_up_server_production

